### ISSUE TITLE
Problems while running a water cluster simulation using the example files

### ISSUE THREAD

**Issue by SamikBose** [paesanilab/mbpol_openmm_plugin#133]
We are trying to follow the guidelines of README.md in the top directory to set up a simulation and running into troubles. 
At this point, we are  working with the water14_cluster.pdb (example file, provided in the python sub-directory) just to have an idea about the inputs and outputs. The default mbpol_config.ini file is used as the input. The  "mbpol_builder mbpol_config.ini generated_script_filename.py" command is generating these error statements:

Traceback (most recent call last):
  File "/usr/bin/mbpol_builder", line 5, in <module>
    pkg_resources.run_script('mbpol==1.0', 'mbpol_builder')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/mbpol-1.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/mbpol_builder", line 64, in <module>
    save_energy_every = config.getint("logging", "save_energy_every", fallback=0)
TypeError: getint() got an unexpected keyword argument 'fallback'

Can you help us understanding what is generating the error and what am I doing wrong?

**Comment by chemphys** [comment]
Hello!

Do you need to use OpenMM, or any MD software would be fine?
We have a more efficient version of MB-pol interfaced with i-pi.
If you are interested in that one, you can find it here: http://paesanigroup.ucsd.edu/software/mbx.html

If you need to use OpenMM, then we can try to contact the main developer and see if he can help.

All the best,
Marc


.   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
Marc Riera-Riambau
Graduate Student @ Paesani Group
University of California, San Diego
Phone: +1 858 750 9866
Mail: mrierari@ucsd.edu
________________________________

**Comment by SamikBose** [comment]
Hi Marc,

Any MD software will do the work for me. I will go through the MB-pol interfaced with i-pi. Thanks for the guidance.
